-- migration_hero_background.sql
-- Fitur: Background Hero (slide otomatis, ganti tiap 10 detik) di
-- beranda publik, diatur admin lewat Panel Admin -> Pengaturan Situs.
--
-- Jalankan file ini SEKALI di Supabase Dashboard -> SQL Editor.
-- Aman dijalankan berkali-kali (pakai IF NOT EXISTS / DROP POLICY IF
-- EXISTS), jadi tidak akan error kalau tidak sengaja dijalankan ulang.

-- 1) Tabel daftar gambar background hero ------------------------------
create table if not exists public.hero_background (
  id bigint generated by default as identity primary key,
  gambar_url text not null,
  urutan integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.hero_background enable row level security;

-- Semua orang (pengunjung situs publik) boleh membaca daftar gambar.
drop policy if exists "hero_background_read_public" on public.hero_background;
create policy "hero_background_read_public"
  on public.hero_background for select
  to anon, authenticated
  using (true);

-- Hanya admin yang sudah login (authenticated) yang boleh
-- tambah/ubah/hapus baris.
drop policy if exists "hero_background_write_admin" on public.hero_background;
create policy "hero_background_write_admin"
  on public.hero_background for all
  to authenticated
  using (true)
  with check (true);

-- 2) Bucket storage untuk file gambar background hero -----------------
insert into storage.buckets (id, name, public)
values ('hero-bg', 'hero-bg', true)
on conflict (id) do nothing;

-- Siapa saja boleh melihat/mengunduh gambar (bucket publik, dipakai
-- untuk tampil di beranda publik).
drop policy if exists "hero_bg_storage_read_public" on storage.objects;
create policy "hero_bg_storage_read_public"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'hero-bg');

-- Hanya admin yang login yang boleh unggah/ubah/hapus file di bucket ini.
drop policy if exists "hero_bg_storage_write_admin" on storage.objects;
create policy "hero_bg_storage_write_admin"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'hero-bg')
  with check (bucket_id = 'hero-bg');
