-- migration_tim_inti.sql
-- Fitur: "Development Team" — bagian KHUSUS di halaman publik
-- tim-pengembang.html, tampil di bawah hero, berisi 5 anggota INTI yang
-- benar-benar mengerjakan pembangunan situs ini (beda dari daftar umum
-- semua anggota KKM Kelompok 05 di tabel `tim_pengembang`).
--
-- Tiap anggota bisa diklik untuk melihat detail (deskripsi + media
-- sosial) lewat modal. Semua field (foto, deskripsi, media sosial) bisa
-- diubah dari Panel Admin -> Tim Inti (Dev Team), tidak perlu edit kode.
--
-- Jalankan file ini SEKALI di Supabase Dashboard -> SQL Editor. Aman
-- dijalankan berkali-kali (pakai IF NOT EXISTS / DROP POLICY IF EXISTS
-- / ON CONFLICT DO NOTHING).

-- 1) Tabel anggota Development Team ------------------------------------
create table if not exists public.tim_inti (
  id bigint generated by default as identity primary key,
  nama text not null,
  jabatan text not null,          -- mis. "Project Coordinator", "Web Developer"
  prodi text,                     -- mis. "Pend. Teknologi Informasi"
  foto_url text,
  deskripsi text,                 -- bio singkat, tampil di modal detail
  instagram text,                 -- boleh username ("nama") atau URL penuh
  whatsapp text,                  -- boleh nomor ("6281234567890") atau URL penuh
  linkedin text,                  -- boleh username atau URL penuh
  email text,
  urutan integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tim_inti enable row level security;

-- Semua orang (pengunjung situs publik) boleh membaca daftar Development Team.
drop policy if exists "tim_inti_read_public" on public.tim_inti;
create policy "tim_inti_read_public"
  on public.tim_inti for select
  to anon, authenticated
  using (true);

-- Hanya admin yang sudah login yang boleh tambah/ubah/hapus.
drop policy if exists "tim_inti_write_admin" on public.tim_inti;
create policy "tim_inti_write_admin"
  on public.tim_inti for all
  to authenticated
  using (true)
  with check (true);

-- 2) Bucket storage untuk foto profil Development Team -----------------
insert into storage.buckets (id, name, public)
values ('tim-inti', 'tim-inti', true)
on conflict (id) do nothing;

drop policy if exists "tim_inti_storage_read_public" on storage.objects;
create policy "tim_inti_storage_read_public"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'tim-inti');

drop policy if exists "tim_inti_storage_write_admin" on storage.objects;
create policy "tim_inti_storage_write_admin"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'tim-inti')
  with check (bucket_id = 'tim-inti');

-- 3) Data awal (5 anggota inti) -----------------------------------------
-- foto_url di bawah mengarah ke file yang sudah ada di /assets (jadi
-- langsung tampil tanpa perlu upload dulu). Silakan ganti foto lewat
-- Panel Admin -> Tim Inti (Dev Team) kapan saja — hasil upload baru akan
-- menimpa foto_url ini dengan URL Supabase Storage.
insert into public.tim_inti (nama, jabatan, prodi, foto_url, urutan)
select * from (values
  ('M. Sailendra Abimanyu', 'Project Coordinator',               'Pend. Pancasila dan Kewarganegaraan', 'assets/dev-abimanyu.png', 1),
  ('Johan Dwi Setyo Utomo', 'Lead Graphic Designer',              'Pend. Matematika',                    'assets/dev-johan.png',    2),
  ('Dedy Indra Setiawan',   'Graphic Designer & Data Researcher', 'Pend. Teknologi Informasi',            'assets/dev-dedy.png',     3),
  ('Edy Sutanto',           'Web Developer',                      'Pend. Teknologi Informasi',            'assets/dev-edy.png',      4),
  ('Muhammad Towil H.',     'Construction Coordinator',           'Pend. Ekonomi',                        'assets/dev-towil.png',    5)
) as seed(nama, jabatan, prodi, foto_url, urutan)
where not exists (select 1 from public.tim_inti);
